Parsing Log File And Filtering Data
daniyalumer/repeated-ip-report pull request #1
Opened 2024-11-07 06:41 UTC by daniyalumer

2024-11-07 12:29 UTC, mzeeshanali requested changes

2024-11-07 12:29 UTC, mzeeshanali commented on main.go
> +type RedirectLog = parser.RedirectLog
why?

2024-11-07 12:29 UTC, mzeeshanali commented on main.go
> +	parser.ParseFile(file, uniqueRedirectLogs, returnLogs)
error handling is missing?

2024-11-07 12:29 UTC, mzeeshanali commented on parser/parser.go
> +
explore time.RFC formats in go

2024-11-07 12:29 UTC, mzeeshanali commented on parser/parser.go
> +
define regexes at one place and use them where needed

2024-11-08 06:25 UTC, daniyalumer commented on parser/parser.go
> +
I have had a look at them

2024-11-08 09:51 UTC, merged